object Versions {
    const val COMPOSE = "1.2.1"
    const val HILT = "2.44"
    const val LIFECYCLE = "2.5.1"
    const val COROUTINES = "1.6.4"
    const val ROOM = "2.4.3"
    const val NAVIGATION = "2.5.2"
    const val MOSHI = "1.14.0"
    const val RETROFIT = "2.9.0"
    const val CORE_KTX = "1.9.0"
    const val COIL = "2.2.2"
    const val MATERIAL3 = "1.0.0-rc01"
    const val KOTLIN = "1.7.20"
    const val GRADLE = "7.3.1"
    const val ESPRESSO = "3.4.0"
    const val JUNIT_ANDROID = "1.1.3"
    const val JUNIT = "4.13.2"
    const val ACTIVITY_COMPOSE = "1.6.0"
}